### PR TITLE
Prevent smoothing rollback

### PR DESCRIPTION
**Pull request by Louka3000**
* Increase max filtering values by a little bit because it's been bothering me for a while.
* Prevent smoothing rollback:

before:
https://github.com/SlimeVR/SlimeVR-Server/assets/20461725/52efbd70-6bc5-4591-869d-14641393c044

after:
https://github.com/SlimeVR/SlimeVR-Server/assets/20461725/d7ea7e33-96bf-40dd-8ddf-89a8e6b7f13e

note: this is 1TPS, slowed down a lot. Actual smoothing wasn't that bad and this was barely noticeable.

### CODE REVIEW

**Review by ButterscotchV — APPROVED** [review]
Kotlinified 🦊

**Comment by ImUrX** [comment]
you should upload the video directly to github, files in discord now have a limited time code in their link, so you will stop being able to watch the video

**Review by ImUrX — COMMENTED** [review]
I see a lot of else now, what happens if tracker filtering is None?

**Comment by Louka3000** [comment]
> I see a lot of else now, what happens if tracker filtering is None?

you get free smoothing

**Review by ImUrX — APPROVED** [review]

**Comment by Louka3000** [comment]
idea64_hvcBMvb3Ob


> I see a lot of else now, what happens if tracker filtering is None?

idea64_hvcBMvb3Ob

**Pull request merged**
