### PR TITLE
Added overlay_protocol

### PR DESCRIPTION
**Pull request by TheButlah**

### CODE REVIEW

**Comment by TheButlah** [comment]
@Eirenliel before I continue, just wanted you to give this a quick glance over. I decided that it might be a bad idea to block the overlay on the advanced union support for flatc-rust, so I introduced a temporary protocol in the meantime. The flatbuffer schema is finished I think, but the `OverlayBridge` is still WIP.

**Comment by Eirenliel** [comment]
> all checks have failed

idk i'm not to fond of the idea of pusing something temporarry in. there is nothing more permanent than temporarry. overlay is not the blocking feature for reviews, imo.

**Comment by Eirenliel** [comment]
Okay then I don't mind.

**Comment by loucass003** [comment]
Is this still needed ? Shoud we close it. @TheButlah ?

**Comment by TheButlah** [comment]
No longer needed now that the main protocol is compatible with rust

**Pull request closed without merging**
