### PR TITLE
Prompt when closing with connected trackers (#24)

### PR DESCRIPTION
**Pull request by Eric13246**
Linked to #24 

The prompt shows up when trying to close SlimeVR while trackers are still connected. I included a setting to let users choose if they want to be warned or not.
I also took the liberty of adding French translations.

This is the first time I work on an open source project, so please review the code I made and give me feedback on what to improve, as I'm sure it won't be perfect the first time!

### CODE REVIEW

**Comment by Louka3000** [comment]
You have commits that shouldn’t be here, please rebase and get rid of them as it messes with the diff on Github.

**Comment by Eric13246** [comment]
Ok, I'll makes these changes later today

**Comment by Louka3000** [comment]
?

**Comment by Eric13246** [comment]
It felt easier to just redo the branch entirely because my commit history was all borked up. I'll create a new PR in a few minutes, unless I can reference my new branch here?

**Comment by Louka3000** [comment]
I don't believe you can change the branch for an existing PR.

 Making a new PR is fine, I won't be the one to cry about it (Git wizards might though)

**Pull request closed without merging**
