### PR TITLE
Additional Theme Options

### PR DESCRIPTION
**Pull request by NWBx01**
Added simple hue shifted themes:
- Green
SlimeVR 4_13_2023 11_56_08 PM
- Yellow
SlimeVR 4_13_2023 11_56_11 PM
- Orange
SlimeVR 4_13_2023 11_56_22 PM
- Red
SlimeVR 4_13_2023 11_56_28 PM
- Dark
SlimeVR 4_13_2023 11_56_31 PM
- Light
SlimeVR 4_13_2023 11_56_34 PM

### CODE REVIEW

**Comment by Louka3000** [comment]
I'm not a fan of just stuffing a bunch of different hues as themes for no reasons except "hey we got more themes and colours!". At this rate we'll have too many themes. Open to counter-arguments tho if people do enjoy being able to choose their favourite colours as themes or something tho.
Bland dark and light themes are a good idea tho, but they need better contrast (and maybe make the dark theme a tiny bit darker?)

**Comment by NWBx01** [comment]
> I'm not a fan of just stuffing a bunch of different hues as themes for no reasons except "hey we got more themes and colours!". At this rate we'll have too many themes.

At the moment, they're called "Color theme". There's not really much room for in-depth customization other than changing the color. To be quite honest, I'm not sure what else you would do with themes otherwise.

> Bland dark and light themes... need better contrast (and maybe make the dark theme a tiny bit darker?)

The contrast of all the themes should be the same since they're a hue shift. It's hard to explain without seeing it yourself, but trying to do themes that have different levels of contrast or color saturation looks "off" when switching between themes. Personally, I think it's ideal to keep the contrast the same between themes, but that's just a personal preference.

**Comment by ImUrX** [comment]
If I add custom themes support and a share feature, would everyone be happy?

**Comment by NWBx01** [comment]
A share feature would be nice. Themes are easy enough to make, but having to build the GUI to add them is a bit of a hurdle for most people.

**Comment by ImUrX** [comment]
i need to make a file format, there is no nice way of "loading css files"

**Comment by TheDevMinerTV** [comment]
There once was a pretty easy to parse format called "JSON". I think you should use it.

**Comment by ImUrX** [comment]
I think im going to use yml... /jk

**Comment by TheDevMinerTV** [comment]
Here's a list of reason why YAML is terrible: https://noyaml.com/

**Comment by Mystium-YT** [comment]
Can you add support to add custom css themes?

**Comment by Mystium-YT** [comment]
Just like import a css file of the colours, no like gui or anything difficult

**Pull request merged**
