### PR TITLE
Add warnings to the tracker selection page

### PR DESCRIPTION
**Pull request by loucass003**

### CODE REVIEW

**Comment by ImUrX** [comment]
need to review this when i have time, wait for me :P

**Review by Eirenliel — APPROVED** [review]

**Review by ButterscotchV — CHANGES_REQUESTED** [review]
Please fix the spelling, also see my recommendations for the warnings.

**Review by ButterscotchV — APPROVED** [review]
I'm happy ^w^

**Comment by ImUrX** [comment]
glad to know :3

**Comment by Louka3000** [comment]
Made some changes to the positions of the circles (lower arms and upper legs a bit higher)
image
Can I commit directly @loucass003 ? You didn't change the lower arms' positions, so I can't just suggest changes on that :p

**Comment by loucass003** [comment]
> Made some changes to the positions of the circles (lower arms and upper legs a bit higher) image Can I commit directly @loucass003 ? You didn't change the lower arms' positions, so I can't just suggest changes on that :p

yes

**Review by Louka3000 — APPROVED** [review]

**Pull request merged**
