### PR TITLE
Add prettier to check formatting during CI linting

### PR DESCRIPTION
**Pull request by TheDevMinerTV**
Blocked by #553

### CODE REVIEW

**Review by Eirenliel — APPROVED** [review]

**Comment by ImUrX** [comment]
Why don’t you push the change to #553

**Review by ButterscotchV — APPROVED** [review]

**Comment by TheDevMinerTV** [comment]
> Why don’t you push the change to #553

it's in your fork of the repo, not in this one

**Comment by ImUrX** [comment]
you still have write perms
image

**Comment by TheDevMinerTV** [comment]
Also, your PR title would be incorrect

**Review by Louka3000 — COMMENTED** [review]
lgtm, but why does CI flag an error (can't reproduce locally)?

**Comment by Eirenliel** [comment]
Plz fix CI, @TheDevMinerTV

**Review by loucass003 — APPROVED** [review]

**Review by ImUrX — APPROVED** [review]

**Pull request merged**
