### PR TITLE
Move serial communication to desktop subproject

### PR DESCRIPTION
**Pull request by ImUrX**
~~Blocked by #755~~

Compare without all the commits from rebase: https://github.com/SlimeVR/SlimeVR-Server/compare/ImUrX:steamvr-desktop...ImUrX:serial-desktop

### CODE REVIEW

**Comment by Eirenliel** [comment]
Serial works on android though, no?

**Comment by ButterscotchV** [comment]
> Serial works on android though, no?

I believe it only works on rooted Android. It's never worked for me or anyone as far as I know.

**Comment by Louka3000** [comment]
Can't get it to work

**Review by Eirenliel — APPROVED** [review]

**Comment by Eirenliel** [comment]
Does it work? if you can't get it to work, @Louka3000 you should block the PR and ask for fixes!

**Review by Louka3000 — CHANGES_REQUESTED** [review]
Indeed does not work

**Review by Louka3000 — APPROVED** [review]
You're an angel

**Pull request merged**
