### PR TITLE
refactor: remove full log and daily log

### PR DESCRIPTION
**Pull request by marcozzxx810**
related to #497 

- [x] remove the daily log (logs in logs folder)
- [x] remove full log (log_main.log)
- [x] remove the logs variable in LoggerManager as daily logs are not needed any more 

Please let me know if there is any other improvement

### CODE REVIEW

**Review by ButterscotchV — APPROVED** [review]
Looks good. If you're looking to add an additional feature, it would be quite nice to have a file size limit for the log file. Something like 50 MB or so? Anything bigger is just excessive and would waste space on people's computers.

Note: We could probably delete these old log files with the SlimeVR installer, maybe we should consider that?

**Comment by marcozzxx810** [comment]
@ButterscotchV It is my pleasure to add this feature, but I may need more clarification and this feature should be regarded as another PR.

What is the expected behavior when it exceeds 50MB?

Proposal:
1. setup two logs (log_last_0.log, log_last_1.log) with 25MB limit
2. rotate the log when the output approximately is equal 25MB size 

Ref:
```
public FileHandler(pattern,
           int limit,
           int count)
     
Initialize a FileHandler to write to a set of files. When (approximately) the given limit has been written to one file, another file will be opened. The output will cycle through a set of count files.
The FileHandler is configured based on LogManager properties (or their default values) except that the given pattern argument is used as the filename pattern, the file limit is set to the limit argument, and the file count is set to the given count argument.

The count must be at least 1.
```
https://docs.oracle.com/javase/7/docs/api/java/util/logging/FileHandler.html#FileHandler(java.lang.String,%20int,%20int)

**Comment by ButterscotchV** [comment]
I was thinking of just cutting off the logging at that point. I really don't think it should be expected to get that large at all, so if it reaches that size, then something really bad has happened and will likely continue to write to it constantly. I'd like to hear Eiren's thoughts on this though. Your proposal does seem like a viable solution if we value the latest logs rather than valuing the earliest logs.

**Comment by marcozzxx810** [comment]
For the removal of the old logs, I guess they will be removed already 

https://github.com/SlimeVR/SlimeVR-Installer/blob/main/windows/web/slimevr_web_installer.nsi#L602

**Review by Eirenliel — APPROVED** [review]

**Comment by Eirenliel** [comment]
> Looks good. If you're looking to add an additional feature, it would be quite nice to have a file size limit for the log file. Something like 50 MB or so? Anything bigger is just excessive and would waste space on people's computers.
> 
> Note: We could probably delete these old log files with the SlimeVR installer, maybe we should consider that?

Plz move to the #497 or another issue to discuss features out of the PRs scope 😛

**Pull request merged**
