### PR TITLE
Fix tracker reset logic

### PR DESCRIPTION
**Pull request by ButterscotchV**
The tracker reset logic was changed in #1057, this broke AutoBone by causing the recorded trackers to be reset. This PR should fix the logic, though I'm not exactly sure what was intended by the logic. I've also added comments because it's not super readable.

### CODE REVIEW

**Review by ImUrX — APPROVED** [review]

**Review by Erimelowo — CHANGES_REQUESTED** [review]
This’ll change behaviour. You should just set the Autobone trackers as internal if you don’t want them reset as that’s what they are

**Comment by ButterscotchV** [comment]
> This’ll change behaviour. You should just set the Autobone trackers as internal if you don’t want them reset as that’s what they are

If I set it to internal, then HumanSkeleton won't accept it. It's not internal anyways, that's not what that flag was supposed to mean. And why should the default behaviour be ignoring the `needsReset` flag?

**Comment by Erimelowo** [comment]
IIRC it’s because the HMD has the needReset flag to false. 
Would need to set that flag to true in the SteamVRDriver class and then there might be a condition to change in the resetHandler or HumanSkeleton.

**Review by Erimelowo — APPROVED** [review]
Good for old behaviour and Autobone seems to work (both tested)

**Pull request merged**
