### PR TITLE
Fix OSC rotations, using OSC with SteamVR and reduce error logging spam

### PR DESCRIPTION
**Pull request by Erimelowo**
- I forgor to send HMD rotation, I just hardcoded what it was when no HMD was present. This worked fine when no SteamVR or when using standalone, but it breaks if using the steamvr driver. Fixed it.
- Reduce the logging amount of AsynchronousCloseException.

### CODE REVIEW

**Comment by Louka3000** [comment]
Rotation is messed up…

**Comment by Louka3000** [comment]
@ButterscotchV I'll E-Transfer you 20$ if you fix the coordinate system.
I just wasted my whole evening on this and I wanna punch my wall and never touch this again.

**Comment by Louka3000** [comment]
Ready for review/merge
Zrock and I tested that it works in VRC as well.

**Review by ButterscotchV — APPROVED** [review]
> Zrock and I tested that it works in VRC as well.

Approved, thanks for confirming it's tested <3

**Pull request merged**
