### PR TITLE
Stop unconditionally hogging serial ports

### PR DESCRIPTION
**Pull request by evg-zhabotinsky**
SlimeVR server was hogging serial ports unconditionally, even when neither provisioning nor serial console were active and serial connection popup was disabled. (Had to manually open serial console and close it to unhog the port.)

Fixed that.

`ProvisioningHandler` registers its serial port discovery handler in constructor and never deregisters it.
The handler was unconditionally opening the ports.
Made it bail out if provisioning isn't running, same way as the provisioning timer handler does.

Verified that provisioning still works as intended, both from the serial connection popup and the setup wizard, and that serial console works normally, regardless if it was opened from popup and from settings.
If popup is disabled or dismissed, and also until user clicks wifi/console button in it, the serial now stays free (checked with vscode serial monitor).

### CODE REVIEW

**Review by Eirenliel — APPROVED** [review]
Good fix. Will need testing before merging.

**Review by ButterscotchV — APPROVED** [review]

**Review by Louka3000 — APPROVED** [review]
LGTM, can test myself when I get slimes if needed

**Comment by evg-zhabotinsky** [comment]
Out of curiosity, what kind of testing is expected? As mentioned, I checked everything serial-related I could think of. Also did run wednesday's dance event with that change (dev build), didn't notice any differences.

**Comment by Eirenliel** [comment]
We need to test it inernally that official slimes can provision wifi properly on our PCs.

**Comment by Louka3000** [comment]
This works fine on my devkit slimes!

**Comment by ImUrX** [comment]
should be merged ^^

**Pull request merged**
