### PR TITLE
Remove old gui

### PR DESCRIPTION
**Pull request by loucass003**
Bye Bye, you wont be missed

### CODE REVIEW

**Comment by TheButlah** [comment]
https://media.tenor.com/4-odaCiEXeUAAAAd/dancing-coffin-coffin-dance.gif

**Comment by loucass003** [comment]
https://user-images.githubusercontent.com/3948904/202874911-88ac57f1-4d58-405b-b007-de260cb16d8c.mp4

**Comment by TheDevMinerTV** [comment]
> Megumin.Best.Explosion.mp4

be careful with copyright LMFAO

**Review by ButterscotchV — APPROVED** [review]
We still don't quite have feature parity on the new GUI, so I'm a bit hesitant to have this PR merged, but at the same time I really want it and I don't think it'll be detrimental.

**Comment by loucass003** [comment]
> We still don't quite have feature parity on the new GUI, so I'm a bit hesitant to have this PR merged, but at the same time I really want it and I don't think it'll be detrimental.

Rn the the new gui is used as the main one. people that don't know how to start the old one, wont use it. i agree that there is small features missing. we should fix it fast but the old gui should go away.

Once the server and gui are merged together i will work on implementing the missing features

**Comment by Eirenliel** [comment]
can i do it myself? 😢

**Comment by Eirenliel** [comment]
I'll do it after GUI merge

**Pull request closed without merging**
