### PR TITLE
Unix socket support

### PR DESCRIPTION
**Pull request by ImUrX**

### CODE REVIEW

**Comment by Eirenliel** [comment]
Please rebase to main

**Comment by ImUrX** [comment]
oh god that rebase was scary

**Comment by Eirenliel** [comment]
Needs testing with https://github.com/SlimeVR/SlimeVR-OpenVR-Driver/pull/27

**Review by Eirenliel — APPROVED** [review]

**Comment by Eirenliel** [comment]
I merged it it's better to start testing and fixing >:

**Pull request merged**
