### PR TITLE
Remove the mounting reset button on the homepage

### PR DESCRIPTION
**Pull request by ButterscotchV**
Use the mounting calibration tab!!

### CODE REVIEW

**Comment by ZRock35** [comment]
OSC users will either need to go through the mounting calibration tab or use tap to mount reset only now?

**Comment by ButterscotchV** [comment]
> OSC users will either need to go through the mounting calibration tab or use tap to mount reset only now?

Yes, everyone should use the mounting calibration tab. idk how I feel about tap to mount reset, but it's the only way so I won't complain. If there's any problems with removing this, let me know.

**Comment by Louka3000** [comment]
Why remove it? It’s convenient and fast

**Comment by ButterscotchV** [comment]
> Why remove it? It’s convenient and fast

Because people just randomly press it expecting it to do magic, plus it's no quicker than the tab for it because you're supposed to do those steps anyways (and you only do it once per session!)

**Comment by Louka3000** [comment]
I’d like to keep it for dev mode then at least, because it’d be a pain to do it via the tab each time I rebuild the server .-.

**Comment by ImUrX** [comment]
Add a warning on non dev mode maybe?

**Review by Louka3000 — APPROVED** [review]

**Comment by Rosdayle** [comment]
Just a comment on the steps on mounting calibration it doesn't include a notice on keeping your heels in place. I would be shifting around to go from standing into a squat/skii pose without knowing to keep my heels in place

**Comment by ButterscotchV** [comment]
You don't necessarily need to keep your heels in the same position, but maybe it could be recommended

**Pull request merged**
