### PR TITLE
Kotlin revolution

### PR DESCRIPTION
**Pull request by ImUrX**

### CODE REVIEW

**Comment by TheButlah** [comment]
I don't think we want the `src/main/java` vs `src/main/kotlin` style. I'd like it to be `.kt` and `.java` files in the same folders preferably.

**Comment by ImUrX** [comment]
Yeah I'm not against the first part.

I didnt touch VRServer tho, only touched Main in purpose to give an example Kotlin file

**Comment by ImUrX** [comment]
how is this?

**Comment by TheButlah** [comment]
This looks good to me.

As an aside: I know things like syntax don't truly matter. But I look at this code and the `var my_var: Type = asdf` is really nice to look at :)

**Review by TheButlah — APPROVED** [review]

**Review by Eirenliel — APPROVED** [review]

**Comment by ImUrX** [comment]
Related to #398

**Pull request merged**
