### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by MaxEvil47**
Very beginnings of Spanish Translation, ~130 lines translated, need context for a few lines.

### CODE REVIEW

**Comment by Louka3000** [comment]
Come over in the Translation - General forum post in our Discord server if you need help with context. (In dev-forum at the bottom.)

**Comment by ImUrX** [comment]
There is an already ongoing translation from another person, you should really come to the discord and talk in the spanish translation channel

**Comment by ReadyPlayerEmma** [comment]
> There is an already ongoing translation from another person, you should really come to the discord and talk in the spanish translation channel

@Fowels has been working on the other translation here: https://github.com/SlimeVR/SlimeVR-Server/pull/396
It was recently committed to GitHub, but has been in progress for some time through discussions in Discord, as you mentioned.

**Comment by Eirenliel** [comment]
Converted to draft because it's not finished and it conflicts with #396. Please coordinate on discord. If this is for Spain Spanish translation, than there is no conflict, but still it needs to be at least mostly finished beefore it can be merged.

**Comment by ImUrX** [comment]
closing because #415 was also made from the same user

**Pull request closed without merging**
