### PR TITLE
Make mounting reset for arms forward

### PR DESCRIPTION
**Pull request by Louka3000**

### CODE REVIEW

**Comment by Eirenliel** [comment]
That's a really hard position to get in 😢

**Comment by Louka3000** [comment]
Frick you’re right… I was testing with arms-only. Doing the rest of the movement kinda breaks the balance ;-;

**Comment by Louka3000** [comment]
Marking as draft. I think a toggle for this would be nice, on the mounting tab or in settings.

**Comment by Louka3000** [comment]
Scratching this PR. I instead want a toggle for T-Pose (vrchat) and another for arms forward (v-tubing). To elaborate, it's not immediately here on my todo list

**Pull request closed without merging**
