### PR TITLE
Create a mapping for remote sensor id to internal.

### PR DESCRIPTION
**Pull request by carl-anders**
This is an up-to-date version of #271 .

I will keep this branch updated to support those with trackers that do not have a contiguous list of sensor id's.
The reason why this is a pull request is for users with this issue to easier find this build.

.jar build as of 2023-01-06:
[slimevr.zip](https://github.com/SlimeVR/SlimeVR-Server/files/10361904/slimevr.zip)

### CODE REVIEW

**Comment by carl-anders** [comment]
I don't think this should be marked as a draft, because any user finding this merge request will assume that the solution doesn't work.

**Comment by Eirenliel** [comment]
we should just finish it and merge

**Comment by carl-anders** [comment]
It is finished?

**Comment by Eirenliel** [comment]
Then we should merge it

**Comment by Eirenliel** [comment]
Is it superceeded by #464?

**Comment by carl-anders** [comment]
#464 is a better solution if it tests out okay.

**Comment by Eirenliel** [comment]
If they solve the same problem, #464 is better. Closing this.

**Pull request closed without merging**
