### PR TITLE
Skeleton Separation Refactor

### PR DESCRIPTION
**Pull request by Louka3000**
This is a relatively big refactor of how we interact with the skeleton. The goal is to make it more like a black box.
The outside should not have direct access to the inside, thus we are now using a HumanPoseManager to get and set everything related to the skeleton (including config)

WIP, as BVH and Autobone still need to be migrated to this new system.

### CODE REVIEW

**Comment by Louka3000** [comment]
This changes the path to the `processor` package, so CODEOWNER will need to be adjusted consequently.

**Comment by Louka3000** [comment]
Also, Autobone needs testing to make sure it still works the same as it’s supposed to.

**Comment by Louka3000** [comment]
sowwy 3:

**Comment by ButterscotchV** [comment]
I can review some of it, but I've contributed some to it so I'm not gonna be able to review all of it properly. I'll try to do a review and state what files I contributed and am unable to review.

**Comment by Eirenliel** [comment]
Please do your best @ButterscotchV. I'll try to look through it until the end of the week.

**Review by Eirenliel — APPROVED** [review]

**Comment by Eirenliel** [comment]
LGTM but needs third pair of eyes

**Review by ButterscotchV — APPROVED** [review]

**Pull request merged**
