### PR TITLE
Small skeleton refactor

### PR DESCRIPTION
**Pull request by TheButlah**
```
- Removed `HumanSkeleton` superclass to simplify hierarchy
* Rename `SimpleSkeleton` to `Skeleton`
```

### CODE REVIEW

**Review by ButterscotchV — APPROVED** [review]
Looks fine to me, maybe `HumanPoseProcessor` could also be renamed to `PoseProcessor` either in this PR or later?

**Review by Louka3000 — APPROVED** [review]

**Comment by Eirenliel** [comment]
I did better in `sekelton-data` branch.

**Comment by TheButlah** [comment]
i agree but skeleton-data isnt merged yet?

**Comment by Eirenliel** [comment]
Why it's not usable? It doesn't seem to break anything. I just want us to have as much refactorning changes pushed in one branch and then get them to `main` so there no problems for others working on stuff

**Comment by Eirenliel** [comment]
Closing it as it will be fully included in PR from skeleton-data soon. If there are additional changes you would want to make to it, make a new PR please.

**Pull request closed without merging**
