### PR TITLE
GUI Updates

### PR DESCRIPTION
**Pull request by dustinduse2**
This adds much to the main layout of the new GUI update.

### CODE REVIEW

**Comment by adigyran** [comment]
i love the number of this PR :) Thanks for continuing my work 👍

**Review by Eirenliel — CHANGES_REQUESTED** [review]
Good stuff, but please remove space from file name, and remove camel case from file names as much as possible (at least from png, use `_`, fxml's are fine with camelCase).

**Comment by dustinduse2** [comment]
Eiren, Thing I got the corrections made. Let me know if there are any others.

**Review by adigyran — APPROVED** [review]
looks fine

**Comment by dustinduse2** [comment]
Hey Also, After merging this in, would you be able to get the new GUI branch caught up to master?

**Comment by adigyran** [comment]
> Hey Also, After merging this in, would you be able to get the new GUI branch caught up to master?

i will merge that

**Comment by dustinduse2** [comment]
> > Hey Also, After merging this in, would you be able to get the new GUI branch caught up to master?
> 
> i will merge that

Cool thank you. I don't know when Ill get time to work on the other GUI stuff. Things are crazy here. Spend half the week at the hospital.

**Comment by adigyran** [comment]
> > > Hey Also, After merging this in, would you be able to get the new GUI branch caught up to master?
> > 
> > 
> > i will merge that
> 
> Cool thank you. I don't know when Ill get time to work on the other GUI stuff. Things are crazy here. Spent half the week at the hospital.

get well :) i will keep it up

**Pull request merged**
