### PR TITLE
Flex resistance and angle support

### PR DESCRIPTION
**Pull request by Erimelowo**
I got tired of maintaining the old branch that got fucked up with 60+ commits. It is still there with old git history if needed: https://github.com/SlimeVR/SlimeVR-Server/pull/1095

Implements flex sensor support for UDP trackers.
This will be able to be used for any joint with a single (more or less...) degree of freedom such as the knee, fingers or even shoulders. Main use is for fingers.
GizmoQC's working repo for flex gloves firmware: https://github.com/Guizmo12/gizmoglovesmocap

Needs https://github.com/SlimeVR/SolarXR-Protocol/pull/149  
Based off https://github.com/SlimeVR/SlimeVR-Server/pull/1091
Closes https://github.com/SlimeVR/SlimeVR-Server/issues/961

### CODE REVIEW

**Review by Eirenliel — COMMENTED** [review]
I need to finalize the protocol in FW and this can be merged

**Comment by Erimelowo** [comment]
There’s apparently a breaking bug somewhere that causes the tracking to feeeze after resetting twice. Been trying to debug it with Gizmo… seems to only happen when a flex tracker is connected tho I think.

apart from that, we also may want to discard old flex data for dynamic calibration (which should be relatively simple)

fingers need to be merged first btw. Maybe with all of this I should mark this as draft?

**Comment by Eirenliel** [comment]
Fingies merged, please rebase

**Comment by Eirenliel** [comment]
SolarXR merged

**Review by Eirenliel — APPROVED** [review]

**Comment by Eirenliel** [comment]
Please fix the build errors

**Review by Eirenliel — APPROVED** [review]

**Review by ButterscotchV — APPROVED** [review]

**Pull request merged**
