### PR TITLE
Remove ReferenceAdjustedTracker

### PR DESCRIPTION
**Pull request by Louka3000**
Merge ReferenceAdjustedTracker into IMUTracker.

This improves the code and 0. and I kinda need this to be able to implement stuff without doing cursed code.

### CODE REVIEW

**Review by Eirenliel — COMMENTED** [review]
There is an important reason it wasn't part of IMU Tracker: because it's not. It could be applied to any tracker, potentially, including trackers that report their absolute rotation and position, that's why it was "layered" like this...

**Comment by Louka3000** [comment]
I know that was the purpose, but, for the example of Vive trackers, we don’t need it, as they’re already going the right direction… all it needs is 1 offset when resetting which is like 2 lines of code…
We don’t have any example currently that would require ReferenceAdjustedTracker afaik.

**Comment by Eirenliel** [comment]
~~here's my example: :nya_gun:~~

**Comment by Louka3000** [comment]
Unless we have a concrete example of Referenceadjustedtracker being useful separate from IMUTracker, there’s no reason to keep it, and for what 0. and I wanna so, it’s much simpler to merge it (and it makes the whole code simpler in general! @loucass003 can back me up on that one :p)

**Pull request merged**
