### PR TITLE
Implement devices and refactor trackers

### PR DESCRIPTION
**Pull request by loucass003**
Implemented Devices. So both UDPTrackers and Feeder VRTrackers have devices and can report infos in the protocol.

The Feeder now declares Devices in the protocol so it can be displayed in the gui.
After that the feeder is probably gonna need an update, i need more infos about the device coming from steamvr.
For now i have put a placeholder for stuff like the manufacturer. (I put "FeederApp" as the manufacturer for now)

In my chase of implementing the device i did a bunch of cleaning the the trackers because it was a mess.

One of the big refactors was to remove the ReferencedAdjustedTracker that was making use do a bunch of wierd tracker replace everywhere, making the code more confusing.
Broke some unit tests on the way, i have no idea how to replace those. Sorry 

Also removed some functions from the Tracker interface into Smaller interfaces so it is easier to know what kind of tracker has what by using instanceof

Also fixed the FastList spliterator

### CODE REVIEW

**Comment by loucass003** [comment]
Also need https://github.com/Eirenliel/slime-java-commons/pull/9 to me merged first

**Comment by loucass003** [comment]
@Eirenliel this is a lot of changes, please dont bonk me <3

**Comment by loucass003** [comment]
Still need some testing thats why it is still a draft

**Comment by Eirenliel** [comment]
Please add description to the PR, or I won't review it :P

**Comment by loucass003** [comment]
> Please add description to the PR, or I won't review it :P

Done sorry <3

**Comment by loucass003** [comment]
Atight i got the message ..... LOL
i am splitting that PR

**Pull request closed without merging**
