### PR TITLE
Update jSerialComm

### PR DESCRIPTION
**Pull request by ImUrX**

### CODE REVIEW

**Comment by TheDevMinerTV** [comment]
It'd be cool if we could have reasonable commit messages...

**Comment by ImUrX** [comment]
i been doing this all day, give me a break

**Comment by Eirenliel** [comment]
> i been doing this all day, give me a break

don't do this all day :nya_a: it's Saturday :nya_gun:

**Review by Louka3000 — APPROVED** [review]
Works on my machine™️

**Review by ButterscotchV — APPROVED** [review]
Sounds fine to me 🦐

**Comment by ImUrX** [comment]
so jSerialComm started getting some new commits, we can merge this and update later or just wait, idc tbh lol

**Pull request closed without merging**
