### PR TITLE
Begone Slimevr-ui.exe

### PR DESCRIPTION
**Pull request by VocalFan**
As long as this doesn't break everything, this solves #971

### CODE REVIEW

**Comment by ImUrX** [comment]
There is #984 already

**Comment by VocalFan** [comment]
That doesn't remove it from the CI.

**Comment by ImUrX** [comment]
ah sorry im dumb

**Comment by VocalFan** [comment]
> ah sorry im dumb

No, you're slime. And us slimes are low iq together :3

**Review by ImUrX — APPROVED** [review]

**Review by Erimelowo — APPROVED** [review]

**Review by Eirenliel — APPROVED** [review]

**Comment by VocalFan** [comment]
Thankies!

**Pull request merged**
